<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
برنامه فضایی
</font>
</h1>

<div dir="rtl">
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

شما تحلیلگر داده در برنامه کاوشگران کهکشان هستید. این برنامه وظیفه دارد بهترین ذهن‌های نسل بعد را برای ماموریت‌های پیچیده فضایی آماده کند. داده‌های پیش روی شما، نتایج آزمون‌های استعدادسنجی از مراکز آموزشی سراسر کشور در دو زمینه حیاتی طی سالیان متوالی است: محاسبات ناوبری (Math) و تحلیل ارتباطات بین‌سیاره‌ای (Reading). فرماندهی کل برنامه برای تعیین استراتژی‌های آینده به تحلیل شما نیاز دارد

</font>
</p>
</div>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazir" color="#0099cc">
        مجموعه‌داده
    </font>
</h2>

<div dir="rtl">
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

به همراه فایل اولیه این سوال، مجموعه‌داده‌ای با نام `data.csv` در پوشه‌ای با نام `Data` قرار گرفته است. این دیتاست شامل نتایج ارزیابی دانش‌آموزان در سال‌های تحصیلی متوالی است. این مجموعه در قالب $48662$ سطر و $6$ ستون در اختیار شما قرار گرفته است که ستون‌های آن به شرح زیر است:
</font>
</p>
</div>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    

| نام ستون | توضیحات |
| :---: | :---: |
| `School Year` | سال تحصیلی که داده‌ها در آن ثبت شده‌اند. |
| `Topic` | مبحث یا موضوع درسی مورد ارزیابی. |
| `Grade` | پایه تحصیلی دانش‌آموزانی که مورد ارزیابی قرار گرفته‌اند. |
| `District` | شناسه عددی و منحصربه‌فرد برای هر منطقه آموزشی. |
| `District Name` | نام رسمی و کامل منطقه آموزشی. |
| `Proficient` | تعداد دانش‌آموزانی که به سطح مهارت مورد نظر (موفق) رسیده‌اند. |
| `Total` | تعداد کل دانش‌آموزانی که در آزمون شرکت کرده و ارزیابی شده‌اند. |

</font>
</div>
</center>

<div dir="rtl">
<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>

   با استفاده از سلول زیر کتابخانه‌های مورد نیاز خود را <code>import</code> کنید و سپس مجموعه‌داده را که در پوشه `Data` قرار دارد وارد محیط توسعه خود کنید.
</font>
</p>
</div>

[Download file](https://quera.org/contest/assignments/84381/download_problem_initial_project/308148/)

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
file_path = r"D:\uni and work\Competitions\Data no3\space\Data\data.csv"
df = pd.read_csv(file_path)

df.head()

   School Year    Topic  Grade  District  Proficient  Total
0         2025  Reading      5      3029        37.0   61.0
1         2021     Math     11      6741        56.0   73.0
2         2023     Math      3       981       105.0  122.0
3         2025     Math      8        27       109.0  120.0
4         2016     Math      4      4572        18.0   23.0

In [30]:
df['School Year'].unique()

array([2025, 2021, 2023, 2016, 2022, 2020, 2019, 2017, 2024, 2014, 2015,
       2018])

In [31]:
df['Grade'].unique()
# df['Topic'].value_counts()

array([ 5, 11,  3,  8,  4,  6,  7, 10])

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazir" color="#0099cc">
        قسمت اول: مراکز آموزشی قابل اتکا
    </font>
</h2>

<div dir="rtl">
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>

برای ماموریت‌های بلندمدت، به فضانوردانی با آموزش بنیادین و پایدار نیاز داریم. به همین منظور نیاز به لیست مدارسی داریم که کیفیت آموزشی پایداری از خود نشان دادند. به عنوان اولین ماموریت از شما می‌خواهیم این مدارس را برای ما پیدا کنید. برای این کار به شرح زیر عمل کنید:

- در مجموعه‌داده اصلی پایه‌هایی را در نظر بگیرید که برای حداقل ۲ سال مختلف داده‌های ثبت شده دارند. این پایه‌ها را «پایه‌های مجاز» می‌نامیم.
- برای هر پایه مجاز، پایدارترین مناطق را از نظر قبول دانش‌آموزان در مجموعه‌داده پیدا کنید. 
- مناطق پایدار برای درس محاسبات ناوبری را در قالب یک دیتافریم در متغیر `stable_math_districts` ذخیره کنید.
- مشابه با درس محاسبات ناوبری، پایدارترین برای درس تحلیل ارتباطات میان‌سیاره‌ای در قالب یک دیتافریم در متغیر `stable_reading_districts` ذخیره کنید.

</font>
<br>
<font face="vazir" color="red">
        خروجی:
</font>

دیتافریم‌ها باید دارای ۲ ستون، با نام‌های `District` و `Grade` باشند که به ترتیب کد منطفه و پایه مورد نظر خواهد بود. همچنین سطرهای آن بر اساس مقادیر ستون `Grade` به ترتیب صعودی مرتب شده باشد. دقت کنید که تعداد سطرهای دیتافریم باید به اندازه تعداد پایه‌های مجاز برای هر درس باشد. دیتافریم زیر می‌تواند نمونه‌ای از قالب کلی خروجی مد نظر باشد:
</p>
</div>

<center>
<div style="line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|Grade|District|
|:---:|:---:|
|1|3829|
|2|201|
|.|.|
|.|.|
|.|.|
|12|48294|
    
</font>
</div>
</center>

In [32]:
df['Proficiency_Rate'] = df['Proficient'] / df['Total']
df.head()

   School Year    Topic  Grade  District  Proficient  Total  Proficiency_Rate
0         2025  Reading      5      3029        37.0   61.0          0.606557
1         2021     Math     11      6741        56.0   73.0          0.767123
2         2023     Math      3       981       105.0  122.0          0.860656
3         2025     Math      8        27       109.0  120.0          0.908333
4         2016     Math      4      4572        18.0   23.0          0.782609

In [33]:
math_df = df[df['Topic'] == 'Math'].copy()
reading_df = df[df['Topic'] == 'Reading'].copy()

math_df.head()

   School Year Topic  Grade  District  Proficient  Total  Proficiency_Rate
1         2021  Math     11      6741        56.0   73.0          0.767123
2         2023  Math      3       981       105.0  122.0          0.860656
3         2025  Math      8        27       109.0  120.0          0.908333
4         2016  Math      4      4572        18.0   23.0          0.782609
5         2022  Math      6      4203        51.0   57.0          0.894737

In [34]:
# For Math: Count unique school years per grade
math_grade_years = math_df.groupby('Grade')['School Year'].nunique()

# Show which grades have how many years of data
print("Math - Years of data per grade:")
print(math_grade_years)

# Filter to keep only grades with 2+ years
math_allowed_grades = math_grade_years[math_grade_years >= 2].index.tolist()
print(f"\nAllowed Math grades: {math_allowed_grades}")

Math - Years of data per grade:
Grade
3      9
4     12
5      9
6      9
7      9
8     12
10     1
11    12
Name: School Year, dtype: int64

Allowed Math grades: [3, 4, 5, 6, 7, 8, 11]

In [35]:
# Filter math_df to only include allowed grades
math_allowed = math_df[math_df['Grade'].isin(math_allowed_grades)]

# Group by Grade AND District, then calculate std of proficiency rates
math_stability = math_allowed.groupby(['Grade', 'District'])['Proficiency_Rate'].std()

# Show first few rows
print("Stability scores (standard deviation) for Math:")
print(math_stability.head(10))

Stability scores (standard deviation) for Math:
Grade  District
3      9           0.075484
       18          0.106259
       27          0.058675
       63          0.045804
       72          0.066999
       81          0.070702
       99          0.085590
       108         0.057740
       126         0.062356
       135         0.071542
Name: Proficiency_Rate, dtype: float64

In [36]:
# For each grade, find the district with minimum std
# We use idxmin() to get the index of minimum value

# First, reset index to make manipulation easier
math_stability_df = math_stability.reset_index()

# For each grade, get the row with minimum std
math_most_stable = math_stability_df.loc[
    math_stability_df.groupby('Grade')['Proficiency_Rate'].idxmin()
]

# Keep only columns we need and sort by grade
stable_math_districts = math_most_stable[['Grade', 'District']].sort_values('Grade')

# Reset index for clean output
stable_math_districts = stable_math_districts.reset_index(drop=True)

print("Most stable Math districts per grade:")
print(stable_math_districts)

Most stable Math districts per grade:
   Grade  District
0      3      4784
1      4      6822
2      5      5922
3      6      1638
4      7      4266
5      8       108
6     11      2349

In [37]:
# Repeat the same process for Reading
reading_grade_years = reading_df.groupby('Grade')['School Year'].nunique()
reading_allowed_grades = reading_grade_years[reading_grade_years >= 2].index.tolist()

# Filter and calculate stability
reading_allowed = reading_df[reading_df['Grade'].isin(reading_allowed_grades)]
reading_stability = reading_allowed.groupby(['Grade', 'District'])['Proficiency_Rate'].std()

# Find most stable per grade
reading_stability_df = reading_stability.reset_index()
reading_most_stable = reading_stability_df.loc[
    reading_stability_df.groupby('Grade')['Proficiency_Rate'].idxmin()
]

# Format output
stable_reading_districts = reading_most_stable[['Grade', 'District']].sort_values('Grade')
stable_reading_districts = stable_reading_districts.reset_index(drop=True)

print("Most stable Reading districts per grade:")
print(stable_reading_districts)

Most stable Reading districts per grade:
   Grade  District
0      3      3715
1      4       261
2      5      1053
3      6      1647
4      7      6957
5      8        72
6     11       108

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazir" color="#0099cc">
        قسمت دوم: بورسیه ملی
    </font>
</h2>

<div dir="rtl">
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
    <font face="vazir" size=3>

قرار است یک بورسیه ملی به یک دانش‌آموز «موفق (Proficient)» که به صورت کاملاً تصادفی از کل کشور در **آخرین سال تحصیلی** انتخاب شده، اهدا شود. ما می‌خواهیم بدانیم این دانش‌آموز نخبه، به احتمال زیاد از کدام منطقه آموزشی (District) می‌آید. به همین منظور لیستی به طول ۱۰ از مناطق آموزشی با بالاترین احتمال انتخاب شدن تهیه کنید و در متغیر `most_probable` ذخیره کنید.    
</font>

<br>
<font face="vazir" color="red">
        خروجی:
</font>

خروجی شما باید در قالب یک دیتافریم با ۲ ستون به نام‌های `District` و `Probability` ذخیره شود که به ترتیب کد منطقه آموزشی و احتمال انتخاب آن‌ها که تا ۳ رقم اعشار رند شده‌اند، باشد. همچنین این دیتافریم باید متشکل از ۱۰ سطر باشد که بر اساس ستون `Probability` و ترتیب نزولی مرتب شده باشند. دیتافریم زیر می‌تواند نمونه‌ای از دیتافریم مورد نظر باشد:

</p>
</div>

<center>
<div style="line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|District|Probability|
|:------:|:---:|
|629471|0.342|
|14|0.328|
|.|.|
|.|.|
|.|.|
|526|0.167|
    
</font>
</div>
</center>

In [38]:
# What is the latest school year in our data?
latest_year = df['School Year'].max()
print(f"The most recent school year is: {latest_year}")

# Let's see what other years exist to confirm
all_years = sorted(df['School Year'].unique())
print(f"All school years: {all_years}")

The most recent school year is: 2025
All school years: [np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]

In [39]:
# Keep only data from the latest school year
latest_data = df[df['School Year'] == latest_year].copy()

print(f"Total rows in latest year: {len(latest_data)}")
print(f"Unique districts in latest year: {latest_data['District'].nunique()}")
print(f"Topics included: {latest_data['Topic'].unique()}")

Total rows in latest year: 5102
Unique districts in latest year: 340
Topics included: ['Reading' 'Math']

In [40]:
# Look at a sample from the latest year
print("Sample from latest year:")
print(latest_data[['Topic', 'Grade', 'District', 'Proficient', 'Total']].head(10))

# Quick check: Are Proficient and Total numbers or already aggregated?
print(f"\nProficient column type: {latest_data['Proficient'].dtype}")
print(f"\nExample: A district with 37.0 proficient out of 61.0 total")
print(f"This means 37 students passed out of 61 tested")

Sample from latest year:
      Topic  Grade  District  Proficient   Total
0   Reading      5      3029        37.0    61.0
3      Math      8        27       109.0   120.0
10     Math      6       355        11.0    12.0
20  Reading      3      6460        41.0    44.0
25     Math      4      4068        24.0    28.0
31     Math      5      4772        31.0    33.0
39  Reading      5      2403        40.0    54.0
55     Math      8      1611       649.0  1026.0
61     Math     10      1278       213.0   258.0
72     Math     11       225       272.0   297.0

Proficient column type: float64

Example: A district with 37.0 proficient out of 61.0 total
This means 37 students passed out of 61 tested

In [41]:
# Group by district and sum the proficient column
district_proficient = latest_data.groupby('District')['Proficient'].sum()

# Let's see what we got
print("Proficient students per district (first 10):")
print(district_proficient.head(10))

# How many districts do we have?
print(f"\nTotal districts with data in {latest_year}: {len(district_proficient)}")

Proficient students per district (first 10):
District
9       487.0
18      287.0
27     1552.0
63      435.0
72       76.0
81      961.0
99      632.0
108     194.0
126    1145.0
135    1036.0
Name: Proficient, dtype: float64

Total districts with data in 2025: 340

In [42]:
# Calculate grand total of all proficient students
total_proficient_nationwide = district_proficient.sum()

print(f"Total proficient students in {latest_year}: {total_proficient_nationwide:.0f}")

Total proficient students in 2025: 403458

In [43]:
# Calculate probability for each district
district_probability = district_proficient / total_proficient_nationwide

print("Probability for each district (first 10):")
print(district_probability.head(10))

# Let's verify: probabilities should sum to 1
print(f"\nSum of all probabilities: {district_probability.sum():.4f}")

Probability for each district (first 10):
District
9      0.001207
18     0.000711
27     0.003847
63     0.001078
72     0.000188
81     0.002382
99     0.001566
108    0.000481
126    0.002838
135    0.002568
Name: Proficient, dtype: float64

Sum of all probabilities: 1.0000

In [44]:
# Sort probabilities in descending order and take top 10
top_10_probabilities = district_probability.sort_values(ascending=False).head(10)

print("Top 10 districts by probability:")
print(top_10_probabilities)

Top 10 districts by probability:
District
1737    0.051059
1053    0.032226
1611    0.027160
3141    0.026724
261     0.024451
6039    0.023636
1863    0.022250
6957    0.021246
6822    0.019477
6795    0.017417
Name: Proficient, dtype: float64

In [45]:
# Create the final DataFrame
most_probable = pd.DataFrame({
    'District': top_10_probabilities.index,
    'Probability': top_10_probabilities.values
})

# Round to 3 decimal places as required
most_probable['Probability'] = most_probable['Probability'].round(3)

# It's already sorted from step 7, but let's be explicit
most_probable = most_probable.sort_values('Probability', ascending=False)

# Reset index for clean output
most_probable = most_probable.reset_index(drop=True)

print("Final output for Part 2:")
print(most_probable)
print(f"\nNumber of rows: {len(most_probable)} (should be 10)")

Final output for Part 2:
   District  Probability
0      1737        0.051
1      1053        0.032
2      1611        0.027
3      3141        0.027
4       261        0.024
5      6039        0.024
6      1863        0.022
7      6957        0.021
8      6822        0.019
9      6795        0.017

Number of rows: 10 (should be 10)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
    <font face="vazir" color="#0099cc">
        قسمت سوم: پیشگامان فناوری پیشران جدید
    </font>
</h2>

<div dir="rtl">
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
    <font face="vazir" size=3>

یک تکنولوژی پیشران جدید فضایی مبتنی بر ریاضیات پیشرفته توسعه یافته‌است. به همین منظور می‌خواهیم ۱۵ منطقه آموزشی که در دو سال اخیر تحصیلی و در آخرین پایه تحصیلی بیشترین رشد معناداری را داشته‌اند انتخاب کنیم و به آن‌ها بودجه تحقیق و توسعه اختصاص دهیم. این مراکز آینده سفرهای فضایی را رقم خواهند زد.

با استفاده از یک آزمون آماری مناسب، ۱۵ منطقه برتر آموزشی در دو سال اخیر تحصیلی را که بیشترین پیشرفت معنادار را داشته‌اند و در متغیر `significant` ذخیره کنید.

</font>
    <br>
    <font face="vazir" color="red">
        خروجی:
    </font>
خروجی شما باید در قالب یک لیست پایتون به اندازه ۱۵ باشد که به ترتیب نزولی مرتب شده باشند. برای داشتن ترتیب نزولی، کافی‌ست لیست به‌صورتی باشد که در اولین عنصر لیست بهترین، عنصر دوم لیست برابر با دومین منطقه آموزشی از نظر پیشرفت معناداری و سومین عنصر برابر با سومین منطقه و ... باشد.
</p>
</div>

In [46]:
# Find the two most recent school years
all_years = sorted(df['School Year'].unique(), reverse=True)  # descending order
print(f"All years (descending): {all_years}")

year2 = all_years[0]  # Most recent
year1 = all_years[1]  # Second most recent

print(f"\nComparing: {year1} vs {year2}")
print(f"Year 1 (older): {year1}")
print(f"Year 2 (newer): {year2}")

# Find the highest grade
highest_grade = df['Grade'].max()
print(f"\nHighest grade in dataset: {highest_grade}")

All years (descending): [np.int64(2025), np.int64(2024), np.int64(2023), np.int64(2022), np.int64(2021), np.int64(2020), np.int64(2019), np.int64(2018), np.int64(2017), np.int64(2016), np.int64(2015), np.int64(2014)]

Comparing: 2024 vs 2025
Year 1 (older): 2024
Year 2 (newer): 2025

Highest grade in dataset: 11

In [47]:
# Filter for Math, highest grade, and our two years
part3_data = df[
    (df['Topic'] == 'Math') & 
    (df['Grade'] == highest_grade) & 
    (df['School Year'].isin([year1, year2]))
].copy()

print(f"Filtered data shape: {part3_data.shape}")
print(f"\nSample of filtered data:")
print(part3_data.head(10))

# Let's see what districts we have
print(f"\nUnique districts: {part3_data['District'].nunique()}")

Filtered data shape: (625, 7)

Sample of filtered data:
     School Year Topic  Grade  District  Proficient  Total  Proficiency_Rate
72          2025  Math     11       225       272.0  297.0          0.915825
141         2025  Math     11      5976        54.0   65.0          0.830769
240         2024  Math     11      2673        34.0   41.0          0.829268
244         2024  Math     11       873        30.0   38.0          0.789474
247         2024  Math     11      5805        60.0   89.0          0.674157
301         2025  Math     11       914        29.0   34.0          0.852941
402         2024  Math     11      6471        21.0   27.0          0.777778
426         2024  Math     11      5510        43.0   47.0          0.914894
450         2024  Math     11      2466        73.0   79.0          0.924051
566         2025  Math     11      5463        67.0   74.0          0.905405

Unique districts: 316

In [48]:
# For each district, check if they have data in both years
district_year_counts = part3_data.groupby('District')['School Year'].nunique()

# Districts with data in both years
districts_with_both = district_year_counts[district_year_counts == 2].index.tolist()

print(f"Districts with data in both {year1} and {year2}: {len(districts_with_both)}")
print(f"Districts with only one year: {district_year_counts[district_year_counts == 1].count()}")

Districts with data in both 2024 and 2025: 309
Districts with only one year: 7

In [49]:
# Filter to only districts with both years
part3_complete = part3_data[part3_data['District'].isin(districts_with_both)]

# Separate into two years
data_year1 = part3_complete[part3_complete['School Year'] == year1]
data_year2 = part3_complete[part3_complete['School Year'] == year2]

print(f"Year {year1}: {len(data_year1)} rows")
print(f"Year {year2}: {len(data_year2)} rows")

# Merge them so we have one row per district with both years
comparison_df = data_year1[['District', 'Proficient', 'Total']].merge(
    data_year2[['District', 'Proficient', 'Total']], 
    on='District', 
    suffixes=('_year1', '_year2')
)

print(f"\nComparison dataframe shape: {comparison_df.shape}")
print("\nFirst few rows:")
print(comparison_df.head())

Year 2024: 309 rows
Year 2025: 309 rows

Comparison dataframe shape: (309, 5)

First few rows:
   District  Proficient_year1  Total_year1  Proficient_year2  Total_year2
0      2673              34.0         41.0              36.0         47.0
1       873              30.0         38.0              25.0         33.0
2      5805              60.0         89.0              89.0        109.0
3      6471              21.0         27.0              23.0         27.0
4      5510              43.0         47.0              39.0         41.0

In [50]:
# Calculate rates for each year
comparison_df['rate_year1'] = comparison_df['Proficient_year1'] / comparison_df['Total_year1']
comparison_df['rate_year2'] = comparison_df['Proficient_year2'] / comparison_df['Total_year2']

# Calculate the improvement (difference in rates)
comparison_df['improvement'] = comparison_df['rate_year2'] - comparison_df['rate_year1']

print("Districts with their improvement:")
print(comparison_df[['District', 'rate_year1', 'rate_year2', 'improvement']].head(10))

# Calculate pooled proportion
comparison_df['p_pooled'] = (
    (comparison_df['Proficient_year1'] + comparison_df['Proficient_year2']) / 
    (comparison_df['Total_year1'] + comparison_df['Total_year2'])
)

# Calculate standard error
comparison_df['std_error'] = np.sqrt(
    comparison_df['p_pooled'] * 
    (1 - comparison_df['p_pooled']) * 
    (1/comparison_df['Total_year1'] + 1/comparison_df['Total_year2'])
)

# Calculate z-score
comparison_df['z_score'] = comparison_df['improvement'] / comparison_df['std_error']

print("\nDistricts with z-scores:")
print(comparison_df[['District', 'improvement', 'z_score']].head(10))

Districts with their improvement:
   District  rate_year1  rate_year2  improvement
0      2673    0.829268    0.765957    -0.063311
1       873    0.789474    0.757576    -0.031898
2      5805    0.674157    0.816514     0.142356
3      6471    0.777778    0.851852     0.074074
4      5510    0.914894    0.951220     0.036326
5      2466    0.924051    0.961165     0.037114
6      5949    0.833333    0.838235     0.004902
7        18    0.958333    0.882353    -0.075980
8      6264    0.803279    0.906250     0.102971
9      3105    0.801980    0.833333     0.031353

Districts with z-scores:
   District  improvement   z_score
0      2673    -0.063311 -0.734472
1       873    -0.031898 -0.320848
2      5805     0.142356  2.309015
3      6471     0.074074  0.700649
4      5510     0.036326  0.674398
5      2466     0.037114  1.089046
6      5949     0.004902  0.078234
7        18    -0.075980 -0.920388
8      6264     0.102971  1.639072
9      3105     0.031353  0.559092

In [51]:
# Filter for districts with positive improvement (they actually got better)
improved_districts = comparison_df[comparison_df['improvement'] > 0].copy()

print(f"Districts with positive improvement: {len(improved_districts)}")
print(f"Districts with negative or zero improvement: {len(comparison_df) - len(improved_districts)}")

# Sort by z-score (highest = most significant improvement)
improved_districts = improved_districts.sort_values('z_score', ascending=False)

print("\nTop improvements by z-score:")
print(improved_districts[['District', 'rate_year1', 'rate_year2', 'improvement', 'z_score']].head(15))

Districts with positive improvement: 203
Districts with negative or zero improvement: 106

Top improvements by z-score:
     District  rate_year1  rate_year2  improvement   z_score
187      1701    0.693750    0.853107     0.159357  3.511983
109      4419    0.641509    0.916667     0.275157  3.292979
148      1989    0.750000    0.976744     0.226744  3.044226
150      4784    0.795000    0.898305     0.103305  3.017813
178      6985    0.803279    0.980392     0.177113  2.914213
270      6592    0.791667    0.975000     0.183333  2.589355
244      4785    0.794118    0.975610     0.181492  2.534763
260      6101    0.812785    0.872727     0.059942  2.439976
259      3204    0.782609    0.955556     0.172947  2.437892
27       1215    0.714286    1.000000     0.285714  2.401636
147      4536    0.850746    0.937500     0.086754  2.364534
78       5166    0.836601    0.925170     0.088569  2.359893
271      6867    0.752212    0.872881     0.120669  2.355422
151      7038    0.827586    0.976190     0.148604  2.344113
26       2322    0.780303    0.888889     0.108586  2.339386

In [52]:
# Take top 15 districts by z-score
top_15_significant = improved_districts.head(15)

# Create the output list as required
significants = top_15_significant['District'].tolist()

print("Top 15 districts with most significant improvement:")
print(significants)
print(f"\nLength: {len(significants)} (should be 15)")

Top 15 districts with most significant improvement:
[1701, 4419, 1989, 4784, 6985, 6592, 4785, 6101, 3204, 1215, 4536, 5166, 6867, 7038, 2322]

Length: 15 (should be 15)

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) در غیر این صورت، در پایان مسابقه نمره شما به صفر تغییر خواهد کرد.
    <br>
    همچنین اگر از کولب برای اجرای این فایل نوت‌بوک استفاده می‌کنید، قبل از ارسال فایل <code>result.zip</code>، آخرین نسخه‌ی نوت‌بوک خود را دانلود کرده و داخل فایل ارسالی قرار دهید.
</font>

In [53]:
import zipfile
import joblib
import os

if not os.path.exists(os.path.join(os.getcwd(), 'space_program.ipynb')):
    %notebook -e space_program.ipynb

stable_math_districts.to_csv('stable_math_districts.csv', index=False)
stable_reading_districts.to_csv('stable_reading_districts.csv', index=False)
most_probable.to_csv('most_probable.csv', index=False)

with open('significants.txt', 'w', encoding='utf-8') as f:
    for item in significants:
        f.write(f"{item}\n")


def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ['stable_math_districts.csv', 'stable_reading_districts.csv', 'most_probable.csv', 'significants.txt', 'space_program.ipynb']
compress(file_names)

File Paths:
['stable_math_districts.csv', 'stable_reading_districts.csv', 'most_probable.csv', 'significants.txt', 'space_program.ipynb']